### ISSUE TITLE
QObject::connect: Cannot queue arguments of type 'QVector<int>' (Make sure 'QVector<int>' is registered using qRegisterMetaType().)

### ISSUE THREAD

**Issue by HuiYuLin** [ZJU-FAST-Lab/Elastic-Tracker#1]
Hello, when I run rviz_sim.launch, the quads in rviz cannot detect the enviroment and it shows 
> QObject::connect: Cannot queue arguments of type 'QVector<int>'
> (Make sure 'QVector<int>' is registered using qRegisterMetaType().)

Is this a reminder that I need to install the QT library? If so, coule you please tell me your QT version?
Thanks!

**Comment by GaaiLam** [comment]
> 

What's your ros version? My QT version is 5.12.8 and the codes are tested both on melodic and noetic.

**Comment by HuiYuLin** [comment]
Thanks for your reply!
My ROS is Melodic. The warning is no longer displayed. But the environment still cannot be detected in RVIZ, as if their are no obstacles. I can run it on ROS Kinetic but cannot run it on my own computer(Melodic). Now the only warning is 
`[ WARN] [1648221581.712987225]: MessageFilter [target=world ]: Discarding message from [unknown] due to empty frame_id.  This message will only print once.
`
I don't know whether it's because I lack some library or some else reasons.
Thanks again!

**Comment by HuiYuLin** [comment]
I have solved it! I forget to modify CUDA parameters in CMakeLists. What a stupid mistake. 
Now the warnning still exists, but it seems to have no matter. The program can run well.
`[ WARN] [1648221581.712987225]: MessageFilter [target=world ]: Discarding message from [unknown] due to empty frame_id. This message will only print once`
Thanks for your reply again, and apologize for taking your time!
