### ISSUE TITLE
Code-related Questions

### ISSUE THREAD

**Issue by zqx789** [ZJU-FAST-Lab/Elastic-Tracker#12]
Could you please explain a little bit the following function "enumerateVs()"? This part puzzled me a long time, I didnt understand the exact meaning of the Matrix A? RowVector b represent the distance between the inner point and the each hyperplane of  polyhedron, right?  hPoly.topRows<3> is the outter normal of each facet, so what you can get by dividing the b?

thank you

 
![Code](https://github.com/ZJU-FAST-Lab/Elastic-Tracker/assets/35356371/1dc32849-1def-4396-86d9-8f0d1115674e)

**Comment by GaaiLam** [comment]
> Could you please explain a little bit the following function "enumerateVs()"? This part puzzled me a long time, I didnt understand the exact meaning of the Matrix A? RowVector b represent the distance between the inner point and the each hyperplane of polyhedron, right? hPoly.topRows<3> is the outter normal of each facet, so what you can get by dividing the b?
> 
> thank you
> 
> ![Code](https://private-user-images.githubusercontent.com/35356371/287296805-1dc32849-1def-4396-86d9-8f0d1115674e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2NTMwODYsIm5iZiI6MTcwMTY1Mjc4NiwicGF0aCI6Ii8zNTM1NjM3MS8yODcyOTY4MDUtMWRjMzI4NDktMWRlZi00Mzk2LTg2ZDktOGYwZDExMTU2NzRlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDAxMTk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkYTM1NDIwMTNkMDc3ZjMyZjI5NTEwMjMyMWZmNDU5NTMzMmRlZjVjNzRmNzVkM2I2MGNiOTQzM2MxYjdkMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9KgdWdCo5FboJT7ZUaiHnRfek5hB7Wl6N2z568hbcwc)

The function "enumerateVs" transfer a polytope from hyperplane representation to Vertex representation. The core idea is using [dual polytope](https://en.wikipedia.org/wiki/Dual_polyhedron). The mentioned codes just do the following procedure: Ax <= b -> Ax <= 1. Then using dual and quickhull, you can get vpoly.

I think you can regard the function as a tool or blackbox, while focusing on the upper level algorithm.
