### ISSUE TITLE
set CUDA=True相机看不到障碍物的问题

### ISSUE THREAD

**Issue by wzya112** [ZJU-FAST-Lab/Elastic-Tracker#13]
![图片](https://github.com/ZJU-FAST-Lab/Elastic-Tracker/assets/93105912/fbea21d8-257f-426c-9882-5145b18e0d6e)
解决办法是：因为cuda版本是12.2，将uav_simulator/src中的CMakeList.txt中的-gencode arch=compute_61,code=sm_61;改为-gencode arch=compute_80,code=sm_80;

**Comment by qycqycqyc** [comment]
非常感谢
