### ISSUE TITLE
catkin build 报这个错怎么解决

### ISSUE THREAD

**Issue by poloar** [ZJU-FAST-Lab/Elastic-Tracker#14]
Errors     << odom_visualization:make /home/zhh/catkin_ws1/logs/odom_visualization/build.make.004.log
/usr/bin/ld: 找不到 -lpose_utils
collect2: error: ld returned 1 exit status
make[2]: *** [/home/zhh/catkin_ws1/devel/.private/odom_visualization/lib/odom_visualization/odom_visualization] Error 1
make[1]: *** [CMakeFiles/odom_visualization.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
/usr/bin/ld: 找不到 -lpose_utils
collect2: error: ld returned 1 exit status
make[2]: *** [/home/zhh/catkin_ws1/devel/.private/odom_visualization/lib/odom_visualization/odom_visualization_car] Error 1
make[1]: *** [CMakeFiles/odom_visualization_car.dir/all] Error 2
make: *** [all] Error 2

**Comment by guitaristff** [comment]
怎么解决的呢
