### ISSUE TITLE
error: ‘const class Eigen::ArrayWrapper<const Eigen::CwiseUnaryOp<Eigen::internal::scalar_quotient1_op<double>, const Eigen::Matrix<double, 3, 1> > >’ has no member named ‘floor’

### ISSUE THREAD

**Issue by GoodLuck0626** [ZJU-FAST-Lab/Elastic-Tracker#2]
Please ask whether the error is due to the eigen version. What version of eigen is used for the code?

**Comment by GaaiLam** [comment]
> 

3.3.7.

I think this code segment of building voxel map can be replaced by other implementations if the compiling error still remains after you change the eigen version.

**Comment by GoodLuck0626** [comment]
> > 
> 
> 3.3.7.
> 
> I think this code segment of building voxel map can be replaced by other implementations if the compiling error still remains after you change the eigen version.

I replaced eigen with 3.3.7, which was successfully compiled. Thank you！！
