### ISSUE TITLE
Tracker does not move

### ISSUE THREAD

**Issue by qingbyin** [ZJU-FAST-Lab/Elastic-Tracker#4]
Hi,
Following the steps in [1-simulation-of-aerial-tracking](https://github.com/ZJU-FAST-Lab/Elastic-Tracker#1-simulation-of-aerial-tracking), the target can move by setting Nav goals,  but the tracker does not move to track the target. The same issue can be seen from another user's video [here](https://www.bilibili.com/video/BV1Q34y187Pm).

**Comment by GaaiLam** [comment]
Perhaps you forgot to change the CUDA option of src/uav_simulator/local_sensing/CMakeLists.txt. You could check if the depth image is received in the simulation.

> Hi, Following the steps in [1-simulation-of-aerial-tracking](https://github.com/ZJU-FAST-Lab/Elastic-Tracker#1-simulation-of-aerial-tracking), the target can move by setting Nav goals, but the tracker does not move to track the target. The same issue can be seen from another user's video [here](https://www.bilibili.com/video/BV1Q34y187Pm).

**Comment by qingbyin** [comment]
Hi Jialin,
Thanks for your clue. After reading the whole code in `local_sensing/CMakeLists.txt`, I realize the depth render is only available with CUDA. The issue is caused by changing `set(ENABLE_CUDA false)`.
