### ISSUE TITLE
source setup.zsh 报错

### ISSUE THREAD

**Issue by lu17** [ZJU-FAST-Lab/Elastic-Tracker#5]
$source devel/setup.zsh
报错：
bash: cd: -q: invalid option
cd: usage: cd [-L|[-P [-e]] [-@]] [dir]
emulate: command not found

**Comment by GaaiLam** [comment]
> $source devel/setup.zsh 报错： bash: cd: -q: invalid option cd: usage: cd [-L|[-P [-e]] [-@]] [dir] emulate: command not found

source devel/setup.bash
