### ISSUE TITLE
the drone0 won't track the target in simulation1.launch

### ISSUE THREAD

**Issue by Arclunar** [ZJU-FAST-Lab/Elastic-Tracker#6]
i set ENABLE_CUDA as false and the  drone0 won't track the target in simulation1.launch
i've checked the topic and found that the drone0/grimap has not publisher
could you please offer some suggestions?

**Comment by GaaiLam** [comment]
> i set ENABLE_CUDA as false and the drone0 won't track the target in simulation1.launch i've checked the topic and found that the drone0/grimap has not publisher could you please offer some suggestions?

I remove the codes about simulating local pointcloud using only cpu. You can refer to [ego-planner](https://github.com/ZJU-FAST-Lab/ego-planner/tree/master/src/uav_simulator/local_sensing) if it's necessary.

**Comment by Arclunar** [comment]
您的邮件已收到，谢谢祝好!
