### ISSUE TITLE
A simple question

### ISSUE THREAD

**Issue by kukulinxin** [ZJU-FAST-Lab/Elastic-Tracker#7]
Is it possible to complete the emulation if the computer does not have a GPU. I tried set(ENABLE_CUDA false) in the CMakeLists file and found that the drone does not track the target during the simulation.

The attached diagram is what the command line window shows when you type "roslaunch planning simulation1.launch"
![2023-04-08 11-37-45 的屏幕截图](https://user-images.githubusercontent.com/114294307/230701533-df314e2f-1034-4676-89e2-8249845a90fb.png)

**Comment by GaaiLam** [comment]
> Is it possible to complete the emulation if the computer does not have a GPU. I tried set(ENABLE_CUDA false) in the CMakeLists file and found that the drone does not track the target during the simulation.
> 
> The attached diagram is what the command line window shows when you type "roslaunch planning simulation1.launch" ![2023-04-08 11-37-45 的屏幕截图](https://user-images.githubusercontent.com/114294307/230701533-df314e2f-1034-4676-89e2-8249845a90fb.png)

Hello, you can refer to the issues #6 , #4

**Comment by kukulinxin** [comment]
> > Is it possible to complete the emulation if the computer does not have a GPU. I tried set(ENABLE_CUDA false) in the CMakeLists file and found that the drone does not track the target during the simulation.
> > The attached diagram is what the command line window shows when you type "roslaunch planning simulation1.launch" ![2023-04-08 11-37-45 的屏幕截图](https://user-images.githubusercontent.com/114294307/230701533-df314e2f-1034-4676-89e2-8249845a90fb.png)
> 
> Hello, you can refer to the issues #6 , #4

I get it.Thank you so much！
