### ISSUE TITLE
想问问关于目标运动预测模块的相关问题

### ISSUE THREAD

**Issue by kukulinxin** [ZJU-FAST-Lab/Elastic-Tracker#8]
在Elastic-tracker中的运动预测模块是通过生成运动基元然后从中取加速度最小的，想问问这样预测的原因是什么，我的理解是这里的运动预测方法本质还是使用了恒速的模型，使用运动基元只是将预测这个问题给离散化。还有就是之前tracker系列的论文中预测这一步一般都是通过一个优化问题来求解，本文不用是因为使用优化的方法计算负载太大了吗？
希望能得到解答，感谢！

**Comment by kukulinxin** [comment]
补充一下：跑仿真时，"car_predict"可视化的路径好像大部分情况下也都是接近直线

**Comment by GaaiLam** [comment]
> 在Elastic-tracker中的运动预测模块是通过生成运动基元然后从中取加速度最小的，想问问这样预测的原因是什么，我的理解是这里的运动预测方法本质还是使用了恒速的模型，使用运动基元只是将预测这个问题给离散化。还有就是之前tracker系列的论文中预测这一步一般都是通过一个优化问题来求解，本文不用是因为使用优化的方法计算负载太大了吗？ 希望能得到解答，感谢！

这样预测单纯是因为方便，就是假设目标匀速运动，除非primitive撞了。
因为elastic-tracker需要优化可视性，所以必须保证预测是无碰的。

**Comment by kukulinxin** [comment]
> > 在Elastic-tracker中的运动预测模块是通过生成运动基元然后从中取加速度最小的，想问问这样预测的原因是什么，我的理解是这里的运动预测方法本质还是使用了恒速的模型，使用运动基元只是将预测这个问题给离散化。还有就是之前tracker系列的论文中预测这一步一般都是通过一个优化问题来求解，本文不用是因为使用优化的方法计算负载太大了吗？ 希望能得到解答，感谢！
> 
> 这样预测单纯是因为方便，就是假设目标匀速运动，除非primitive撞了。 因为elastic-tracker需要优化可视性，所以必须保证预测是无碰的。

感谢感谢

**Comment by kukulinxin** [comment]
> > 在Elastic-tracker中的运动预测模块是通过生成运动基元然后从中取加速度最小的，想问问这样预测的原因是什么，我的理解是这里的运动预测方法本质还是使用了恒速的模型，使用运动基元只是将预测这个问题给离散化。还有就是之前tracker系列的论文中预测这一步一般都是通过一个优化问题来求解，本文不用是因为使用优化的方法计算负载太大了吗？ 希望能得到解答，感谢！
> 
> 这样预测单纯是因为方便，就是假设目标匀速运动，除非primitive撞了。 因为elastic-tracker需要优化可视性，所以必须保证预测是无碰的。

感谢你的回复，那这样的话预测的精度感觉不如优化的方法，对跟踪的效果会不会有影响呀

**Comment by GaaiLam** [comment]
> > > 在Elastic-tracker中的运动预测模块是通过生成运动基元然后从中取加速度最小的，想问问这样预测的原因是什么，我的理解是这里的运动预测方法本质还是使用了恒速的模型，使用运动基元只是将预测这个问题给离散化。还有就是之前tracker系列的论文中预测这一步一般都是通过一个优化问题来求解，本文不用是因为使用优化的方法计算负载太大了吗？ 希望能得到解答，感谢！
> > 
> > 
> > 这样预测单纯是因为方便，就是假设目标匀速运动，除非primitive撞了。 因为elastic-tracker需要优化可视性，所以必须保证预测是无碰的。
> 
> 感谢你的回复，那这样的话预测的精度感觉不如优化的方法，对跟踪的效果会不会有影响呀

其实不见得精度就不如优化方法，因为人的运动很随机，历史的信息并不会对未来的轨迹产生多大预测作用，相反用拟合的方法反而可能会过分考虑历史的信息，所以干脆简单点用匀速假设好了。实际效果也还好，毕竟对目标预测精度的要求没那么高，包括尺度估计也是直接近大远小估计的，检测这一环节的精度已经不怎么高了。

**Comment by kukulinxin** [comment]
> > > > 在Elastic-tracker中的运动预测模块是通过生成运动基元然后从中取加速度最小的，想问问这样预测的原因是什么，我的理解是这里的运动预测方法本质还是使用了恒速的模型，使用运动基元只是将预测这个问题给离散化。还有就是之前tracker系列的论文中预测这一步一般都是通过一个优化问题来求解，本文不用是因为使用优化的方法计算负载太大了吗？ 希望能得到解答，感谢！
> > > 
> > > 
> > > 这样预测单纯是因为方便，就是假设目标匀速运动，除非primitive撞了。 因为elastic-tracker需要优化可视性，所以必须保证预测是无碰的。
> > 
> > 
> > 感谢你的回复，那这样的话预测的精度感觉不如优化的方法，对跟踪的效果会不会有影响呀
> 
> 其实不见得精度就不如优化方法，因为人的运动很随机，历史的信息并不会对未来的轨迹产生多大预测作用，相反用拟合的方法反而可能会过分考虑历史的信息，所以干脆简单点用匀速假设好了。实际效果也还好，毕竟对目标预测精度的要求没那么高，包括尺度估计也是直接近大远小估计的，检测这一环节的精度已经不怎么高了。

大概能明白你说所说的含义，对我也有所启发，感谢
